name: riverpod_architecture_example
description: A quick example

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1
environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  collection: ^1.17.0
  font_awesome_flutter: ^10.4.0
  flex_color_scheme: ^7.0.4
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.2.0
  go_router: ^6.5.8
  google_fonts: ^4.0.4
  hooks_riverpod: ^2.3.6
  json_annotation: ^4.8.0
  logging: ^1.1.1
  package_info_plus: ^3.1.2
  riverpod_annotation: ^2.1.1
  shared_preferences: ^2.1.0
  stack_trace: ^1.11.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  go_router_builder: ^1.2.2
  json_serializable: ^6.6.1
  riverpod_generator: ^2.2.1
