name: riverpod_weather
description: "A simple example on how to use riverpod with some clean architecture"
version: 1.1.0+2
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  cached_network_image: ^3.3.0
  collection: ^1.18.0
  connectivity_plus: ^6.1.4
  dio: ^5.4.0
  flex_color_scheme: ^8.2.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.3.0
  flutter_hooks: ^0.21.2
  flutter_localizations:
    sdk: flutter
  flutter_use: ^1.0.0
  font_awesome_flutter: ^10.6.0
  freezed_annotation: ^3.1.0
  geolocator: ^14.0.2
  go_router: ^16.1.0
  google_fonts: ^6.1.0
  hooks_riverpod: ^2.4.9
  internet_connection_checker: ^3.0.1
  intl: ^0.20.2
  json_annotation: ^4.8.1
  package_info_plus: ^8.0.0
  path_provider: ^2.1.1
  retrofit: ^4.1.0
  riverpod_annotation: ^2.3.3
  stack_trace: ^1.11.1
  talker_dio_logger: ^4.0.0
  talker_flutter: ^4.0.0
  drift: ^2.18.0
  sqlite3_flutter_libs: ^0.5.0

dev_dependencies:
  build_runner: ^2.4.7
  custom_lint: ^0.7.6
  flutter_gen: ^5.3.2
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.1.0
  go_router_builder: ^3.0.0
  json_serializable: ^6.7.1
  mocktail: ^1.0.2
  retrofit_generator: ^9.7.0
  riverpod_generator: ^2.6.4
  riverpod_lint: ^2.6.4
  very_good_analysis: ^9.0.0
  drift_dev: ^2.18.0

assets:
  - .env.json

flutter:
  uses-material-design: true
  generate: true
